literacy_network/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # the home view will handle a redirection on the basis of user account type
    url(r'^$', 'literacy_network.views.home_redirect', name='home'),
    url(r'^volunteers/$', 'literacy_network.views.volunteers', name='volunteers'),
    url(r'^volunteers/new$', 'literacy_network.views.create_volunteer', name='new-volunteer'),
    url(r'^volunteers/edit/(?P<volunteer_id>\d{1,10})/$', 
        RedirectView.as_view(pattern_name='edit-volunteer-profile'), 
            name='edit-volunteer'),
    url(r'^volunteers/view/(?P<volunteer_id>\d{1,10})$', 
        'literacy_network.views.view_volunteer', name='view-volunteer'),
    url(r'^volunteers/profile/(?P<volunteer_id>\d{1,10})/(?P<hide_contact_form>True|False)?$', 
        'literacy_network.views.edit_volunteer_profile', name='edit-volunteer-profile'),
    url(r'^upload-industries$', 'literacy_network.views.upload_industries', name='industries'),
    url(r'^thanks$', 'literacy_network.views.thanks', name='thanks'),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name="auth_login"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {"next_page" : "/logged-out"}, name="auth_logout"),
    url(r'^logged-out$', 'literacy_network.views.logged_out', name="logged_out"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/volunteers/+$', 'literacy_network.views.volunteers', name='volunteers'),
    url(r'^admin/', include(admin.site.urls)),
)

literacy_network/models.py
# Contains definitions of database entities
from django.db import models
from django.contrib.auth.models import User
from localflavor.us.models import USStateField

class Industry(models.Model):
	"""Represents industries that volunteers may have experience in"""

	def __unicode__(self):
		return self.name

	name = models.CharField(max_length=100, verbose_name = 'industry name')
	code = models.CharField(max_length=10)

	class Meta:
		verbose_name_plural = "industries"

class Site(models.Model):
    """ Represents a location/office where a volunteer can participate """
    name = models.CharField(max_length=100, unique=True)
    

class Volunteer(models.Model):
    """ Represents a volunteer which has skills and time to donate """
    first_name = models.CharField(max_length=200, 
            verbose_name = 'volunteer\'s first name')
    last_name = models.CharField(max_length=200, 
            verbose_name = 'volunteer\'s last name')
    phone = models.CharField(max_length=12, verbose_name = 'volunteer\'s phone number')

    address_line1 = models.CharField(max_length=100, null=True, blank=True)
    address_line2 = models.CharField(max_length=100, null=True, blank=True)
    state = USStateField(null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    zipcode = models.CharField(max_length=10, null=True, blank=True)

    occupation_notes = models.TextField(null=True, blank=True)
    volunteer_notes = models.TextField(null=True, blank=True)

    is_public = models.BooleanField(default=False)
    linkedin_link = models.CharField(max_length=100, null=True, blank=True)

    user = models.ForeignKey(User, null=True, blank=True)

class Occupation(models.Model):
    """ An occupation held by a volunteer for some time period """
    volunteer = models.ForeignKey(Volunteer)
    job_title = models.CharField(max_length=50)
    industry = models.ForeignKey(Industry, verbose_name="Industry")
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

class VolunteerSite(models.Model):
    """ Mapping between volunteers and the sites they work at """
    volunteer = models.ForeignKey(Volunteer)
    site = models.ForeignKey(Site)

    # indicates if the volunteer is willing to go to the site
    affirmative = models.BooleanField()

    def __unicode__(self):
        return unicode(self.site.name)

class HelpType(models.Model):
    """ A type of participation that a volunteer is willing to """
    short_name = models.CharField(max_length=10)
    description = models.CharField(max_length=150)
    has_details = models.BooleanField()
    help_text = models.CharField(max_length=500)

class HelpTypeResponse(models.Model):
    volunteer = models.ForeignKey(Volunteer)
    affirmative = models.BooleanField(default=False)
    help_type = models.ForeignKey(HelpType)
    details = models.TextField(null=True, blank=True)

literacy_network/forms.py
from django import forms
from literacy_network.models import *
from django.forms.models import modelformset_factory, inlineformset_factory

class VolunteerForm(forms.ModelForm):
    class Meta:
        model = Volunteer

class UserForm(forms.ModelForm):
    class Meta:
        model = User

class UserEditForm(forms.ModelForm):   
    class Meta:
        model = User
        fields = ('username', )

    def save(self, commit=True):
        user = super(UserEditForm, self).save(commit=False) 

class OccupationForm(forms.ModelForm):
    class Meta:
        model = Occupation
        exclude = ['start_date', 'end_date']

HelpResponseFormset = inlineformset_factory(
    Volunteer, HelpTypeResponse, extra=0, can_delete=False)
OccupationFormset = inlineformset_factory(
    Volunteer, Occupation, form=OccupationForm, extra=3, can_delete=False)
SiteFormset = inlineformset_factory(
    Volunteer, VolunteerSite, extra=0, can_delete=False)

literacy_network/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_protect
from datetime import datetime, timedelta
from django.db import DatabaseError
from django.utils import simplejson
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from literacy_network.models import *
from literacy_network.forms import *
from django.core.exceptions import PermissionDenied
import csv, sys, os
from django.contrib.auth import authenticate, login

def home_redirect(request):
    """ Redirects the user to a registration form or volunteer list 
        depending on their account role 
    """
    if request.user.is_authenticated() and request.user.is_staff:
        return redirect("volunteers")
    elif request.user.is_authenticated() and not request.user.is_superuser:
        related_volunteer = get_object_or_404(Volunteer, user_id=request.user.pk)
        return redirect("edit-volunteer-profile", volunteer_id=related_volunteer.pk)
    else:
        return redirect("new-volunteer")

def logged_out(request):
    """ Renders a page notifying the user that they have logged out
        and points them back to the organization's main site
    """
    return render(request, "logged-out.html")

def create_volunteer(request, volunteer_id=None):
    """ Presents a view used to edit a volunteer

        Keyword arguments:
            volunteer_id -- The primary key of the volunteer
                        to edit, or None to perform an add
        Returns a view used to edit the volunteer on GET,
            or a redirection to the volunteer list on POST
    """
    volunteer = None
    try:
        volunteer = Volunteer.objects.get(id=volunteer_id)
        user = User.objects.get(id=volunteer.user_id)
    except Volunteer.DoesNotExist:
        vol_form = VolunteerForm()
        user_form = UserCreationForm()
        user = User()
    except User.DoesNotExist:
        user_form = UserCreationForm()

    if request.method == "POST":
        vol_form = VolunteerForm(request.POST, request.FILES)
        user_form = UserCreationForm(request.POST, request.FILES)

        if vol_form.is_valid() and user_form.is_valid():
            svol = vol_form.save()
            user = user_form.save()

            # associate the user with the volunteer
            svol.user = user
            svol.save()
            user = authenticate(username=user.username, password=user_form.clean_password2())
            login(request, user)

            return redirect("edit-volunteer-profile", 
                volunteer_id=svol.id, hide_contact_form=True)
    elif volunteer_id:
        vol_form = VolunteerForm(instance=volunteer)
        if user:
            user_form = UserCreationForm(instance=user)

    return render(request, 'edit-volunteer.html', 
        {"vol_form" : vol_form, "user_form" : user_form })
         
@login_required
def edit_volunteer_profile(request, volunteer_id, hide_contact_form=False):
    volunteer = get_object_or_404(Volunteer, pk=volunteer_id)
    if (volunteer.user and request.user.pk != volunteer.user.pk) and not request.user.is_superuser:
        raise PermissionDenied()

    # make sure there is a record for each volunteer help type
    new_helps = [q for q in HelpType.objects.all()
                    if not q in [r.help_type for r in 
                             volunteer.helptyperesponse_set.all()]]
    for helptype in new_helps:
        resp = HelpTypeResponse.objects.create(volunteer=volunteer, 
                help_type=helptype, affirmative=False)

    # make sure there is a record for each class site
    new_sites = [s for s in Site.objects.all()
                    if not s in [r.site for r in volunteer.volunteersite_set.all()]]
    for site in new_sites:
        addsite = VolunteerSite.objects.create(volunteer=volunteer, 
                            site=site, affirmative=False)

    if request.method == 'POST':
        vol_form = VolunteerForm(request.POST, instance=volunteer)
        user_form = UserEditForm(request.POST, instance=request.user)
        occ_formset = OccupationFormset(request.POST, 
            prefix="occ", instance=volunteer)
        help_formset = HelpResponseFormset(request.POST, 
            prefix="help", instance=volunteer)
        site_formset = SiteFormset(request.POST, 
            prefix="site", instance=volunteer)

        if occ_formset.is_valid() and help_formset.is_valid() \
            and site_formset.is_valid() and vol_form.is_valid() \
            and user_form.is_valid():
            vol_form.save()
            occ_formset.save()
            help_formset.save()
            site_formset.save()
            return render(request, 'thanks.html')
        else:
            print("Vol form errors")
            print(vol_form.errors)
            print("Occ form errors")
            print(occ_formset.errors)
            print("Help form errors")
            print(help_formset.errors)
            print("Site form errors")
            print(site_formset.errors)
    else:
        vol_form = VolunteerForm(instance=volunteer)
        user_form = UserEditForm(instance=request.user)
        occ_formset = OccupationFormset(instance=volunteer, prefix="occ")
        help_formset = HelpResponseFormset(instance=volunteer, prefix="help")
        site_formset = SiteFormset(instance=volunteer, prefix="site")

    return render(request, 'edit_profile.html', {
        "vol_form" : vol_form,
        "user_form" : user_form,
        'occ_formset' : occ_formset,
        'help_formset' : help_formset,
        "site_formset" : site_formset,
        "anchor" : None,
        "hide_contact_form" : hide_contact_form,
        "willvisit" : volunteer.volunteersite_set.filter(affirmative=True).count() > 0
    })

def view_volunteer(request, volunteer_id):
    """ Opens a page for staff members or the public 
        (if the profile is public-enabled) to view a volunteer
    """
    volunteer = get_object_or_404(Volunteer, pk=volunteer_id)
    if not volunteer.is_public and not \
        (request.user.is_authenticated and 
            (request.user.is_superuser or request.user.is_staff
                (volunteer.user and request.user.pk == volunteer.user.pk))):
        raise PermissionDenied()
    return render(request, "view-volunteer.html", {"volunteer" : volunteer})
    
@user_passes_test(lambda u: u.is_staff)
def volunteers(request):
    """ Presents a list of volunteers """
    volunteers = Volunteer.objects.all()
    return render(request, 'volunteers.html',
            {"volunteers" : volunteers})

    return render(request, 'edit-volunteer.html',
        {"form" : form})

def upload_industries(request):
    '''Handles upload of industry data in CSV format'''
    if request.method == "POST":
        for row in csv.DictReader(request.FILES["industries-csv"]):
            industry = Industry()
            industry.code=row["Industry_Code"]
            industry.name=row["Industry_Name"]
            industry.save()
        return redirect("/")
    else:
        return render(request, "upload-industries.html")

    return redirect("/")

def thanks(request):
    return render(request, "thanks.html")

literacy_network/templates/contact-form.html
{% load tabindex from tag_extras %}
{% load currency from tag_extras %}
{% load bool_yn from tag_extras %}
{% load widget_tweaks %}

<div class="form-group">
    <label for="id_first_name" class="col-md-2 control-label">First Name</label>
    {{ vol_form.first_name.errors }}
    {{ vol_form.first_name|add_class:"form-control" }}
</div>

<div class="form-group">
    <label for="id_last_name" class="col-md-2 control-label">Last Name</label>
    {{ vol_form.last_name.errors }}
    {{ vol_form.last_name|add_class:"form-control" }}
</div>

<div class="form-group">
    <label for="id_username" class="col-md-2 control-label">Contact Email</label>
    {{ user_form.username|add_class:"form-control" }}
</div>

<div class="form-group">
    <label for="id_phone" class="col-md-2 control-label">Contact Phone</label>
    {{ vol_form.phone.errors }}
    {{ vol_form.phone|add_class:"form-control" }}
</div>

<div class="form-group">
    <label for="id_address_line1" class="col-md-2 control-label">Address</label>
    {{ vol_form.address_line1|add_class:"form-control" }}
</div>

<div class="form-group">
    <label for="id_address_line2" class="col-md-2 control-label">&nbsp;</label>
    {{ vol_form.address_line2|add_class:"form-control" }}
</div>

<div class="form-group">
    <label for="id_city" class="col-md-2 control-label">City</label>
    {{ vol_form.city|add_class:"form-control"}}
</div>

<div class="form-group">
    <label for="id_state" class="col-md-2 control-label">State</label>
    {% render_field vol_form.state type="select" class="form-control" style="width:12em;" %}
</div>

<div class="form-group">
    <label for="id_zipcode" class="col-md-2 control-label">Zip</label>
    {{ vol_form.zipcode|add_class:"form-control"|attr:"style:width:12em;" }}
</div>

literacy_network/templates/edit-volunteer.html
{% load tabindex from tag_extras %}
{% load currency from tag_extras %}
{% load bool_yn from tag_extras %}
{% load widget_tweaks %}
{% include "topmatter.html" %}

<div class="row">

    <form method="post" action="" role="form" class="col-md-6 col-md-offset-2">
        {% csrf_token %}

        <h3>Contact Information</h3>
        {{ vol_form.non_field_errors }}
        {% csrf_token %}
        {% include "contact-form.html" %}

        <div class="form-group">
            <label for="id_username" class="col-md-2 control-label">Password</label>
            {{ user_form.password1|add_class:"form-control" }}
            {{ user_form.password1.errors }}
        </div>

        <div class="form-group">
            <label for="id_username" class="col-md-2 control-label">Confirm Password</label>
            {{ user_form.password2 |add_class:"form-control"}}
            {{ user_form.password2.errors }}
        </div>

        <button class="btn btn-primary col-md-offset-2" type="submit">Next</button>
    </form>
</div>
{% include "footer.html" %}

literacy_network/templates/edit_profile.html
{% load tabindex from tag_extras %}
{% load currency from tag_extras %}
{% load bool_yn from tag_extras %}
{% load widget_tweaks %}

{% include "topmatter.html" %}

<div class="row">

    <form method="post" action="" role="form" class="col-md-6 col-md-offset-2">
        {% csrf_token %}
        {{ occ_formset.management_form }}
        {{ site_formset.management_form }}
        {{ help_formset.management_form }}

        <div style="display: {{hide_contact_form|yesno:'none, block'}}">
            <h3>Contact Information</h3>
            {% include "contact-form.html" %}
        </div>

        <h3>Career Information</h3>

        <table class="table-responsive">
            <thead>
            <tr>
                <th>What fields did or do you work in?</th>
                <th>Job Title</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <div class="form-group">
                        {{ occ_formset.forms.0.industry |add_class:"form-control" }}
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        {{ occ_formset.forms.0.job_title |add_class:"form-control" }}
                        {{ occ_formset.forms.0.id |add_class:"form-control" }}
                    </div>
                </td>
            </tr>
            {% for occ_form in occ_formset|slice:"1:" %}
            {{ occ_form.id }}
            <tr class="more-occ" style="display: none">
                <td>
                    <div class="form-group">
                        {{ occ_form.industry|add_class:"form-control" }}
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        {{ occ_form.job_title|add_class:"form-control" }}
                    </div>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <a id="add-more-occ-link">Add more occupations</a>

        <h3>Volunteer Information</h3>

        <p>How would you like to volunteer?</p>

        {% for help_form in help_formset %}
        <div class="form-group">
            <div class="checkbox">
                <label>
                    {{ help_form.help_type.as_hidden }}
                    {{ help_form.id }}
                    {{ help_form.affirmative }}
                    {{ help_form.instance.help_type.description }}
                </label>
            </div>
        </div>
        {% endfor %}

        <div class="form-group">
            <div class="checkbox">
                <label>
                    <input type="checkbox" data-bind="checked: willvisit"/> Visit classes as a guest speaker
                </label>
            </div>
        </div>
        
        <div style="padding-left: 3em;" data-bind="visible: willvisit">
            <p>Which sites could you visit?</p>
            <ul style="list-style-type: none; margin-left: 30px;">
                {% for site_form in site_formset %}
                {{ site_form.site.as_hidden }}
                {{ site_form.id }}
                <li>{{ site_form.affirmative }} {{ site_form.instance.site.name }}</li>
                {% endfor %}
                <ul>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        {% if anchor %}
            location.hash = "#" + {{ anchor }}
        {% endif %}
        
        $("#add-more-occ-link").click(function(e) {
            e.preventDefault();
            $(".more-occ").show();
            $("#add-more-occ-link").hide();
        });

        var viewModel = {
            willvisit: ko.observable({{willvisit|yesno:"true,false"}})
        };
        viewModel.willvisit.subscribe(function(oldValue) {
            if(!oldValue) {
                window.scrollTo(0,document.body.scrollHeight);
            }
        }, null, "beforeChange");
        ko.applyBindings(viewModel);
    });

</script>

{% include "footer.html" %}

literacy_network/templates/footer.html
</div>
<div id="footer">
</div>

</div>

<div style="clear:both;"></div>
</div>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/datatables.bootstrap.js"></script>
</body>
</html>

literacy_network/templates/home.html
{% load tabindex from tag_extras %}
{% load currency from tag_extras %}
{% load bool_yn from tag_extras %}
{% include "topmatter.html" %}

<form method="post" action="">
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="right">

        <label for="id_name">Name</label>
        {{ form.name.errors }}
        {{ form.name }}

        <label for="id_phone">Contact Phone</label>
        {{ form.phone.errors }}
        {{ form.phone }}

        <label for="id_email">Contact Email</label>
        {{ form.email.errors }}
        {{ form.email }}

    </div>

</form>

{% include "footer.html" %}

literacy_network/templates/logged-out.html
{% load tabindex from tag_extras %}
{% load currency from tag_extras %}
{% load bool_yn from tag_extras %}
{% include "topmatter.html" %}

You have successfully logged out. Thanks for visiting!

{% include "footer.html" %}

literacy_network/templates/logout.html
{% load tabindex from tag_extras %}
{% load currency from tag_extras %}
{% load bool_yn from tag_extras %}
{% include "topmatter.html" %}

You have successfully logged out. Thanks for visiting!

{% include "footer.html" %}

literacy_network/templates/thanks.html
<html>
<head><title>Thanks!</title></head>
<body>
Thanks for participating.
</body>
</html>

literacy_network/templates/topmatter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Literacy Network</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if lt IE 7]>
    <link rel="stylesheet" type="text/css" href="/static/css/style-ie.css"/>
    <![endif]-->
    <script type="text/javascript" src="/static/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/static/js/TableTools.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery.formset.js"></script>
    <script type="text/javascript" src="/static/js/jquery.uniform.js"></script>
    <script type="text/javascript" src="/static/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script type="text/javascript" src="/static/js/knockout-3.0.0.js"></script>
    <script type="text/javascript" src="/static/js/application.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.dataTables.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/TableTools.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/uniform.default.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/overcast/jquery-ui-1.10.3.custom.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/datatables.bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	   <a href="/" class="navbar-brand"><img src="/static/images/logo2.png" width=150/></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
				{% if not user.is_authenticated %}
				<a href="{% url 'django.contrib.auth.views.login' %}">Log In</a>
				{% else %}
				<a href="{% url 'django.contrib.auth.views.logout' %}">Log Out</a>
				{% endif %}
		</li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">

literacy_network/templates/upload-industries.html
{% include "topmatter.html" %}

<form method="POST" action="/upload-industries" enctype="multipart/form-data" role="form">
        {% csrf_token %}
        <input type="file" name="industries-csv"></input>
        <input type="submit" class="round-button"></input>
    </form>

{% include "footer.html" %}

literacy_network/templates/view-volunteer.html
{% load tabindex from tag_extras %}
{% load currency from tag_extras %}
{% load bool_yn from tag_extras %}
{% include "topmatter.html" %}

{{ volunteer.first_name }} {{ volunteer.last_name }}<br>
{{ volunteer.user.username }}<br>
{{ volunteer.phone }}<br>
{{ volunteer.address_line1 }}<br>
{{ volunteer.address_line2 }}<br>
{{ volunteer.city }}, {{ volunteer.state }} {{ volunteer.zipcode }}<br>
{% for occ in volunteer.occupation_set.all %}
	{{ occ.industry }}: {{ occ.job_title }}<br>
{% endfor %}
{{ volunteer.occupation_notes }}<br>
{% for resp in volunteer.helptyperesponse_set.all %}
	{{ resp.help_type.short_name }}: {{ resp.affirmative|bool_yn }}<br>
{% endfor %}
Visit: {{ volunteer.volunteersite_set.all|join:", " }}

{% include "footer.html" %}

literacy_network/templates/volunteers.html
{% load tag_extras %}
{% include "topmatter.html" %}

<div class="row">
    <div class="col-md-12">
        <h3>Volunteers</h3>

        <table id="data-table">

            <thead id="titles">
            <tr>
                <th>Name</th>
                <th>Contact</th>
                <th>Industry</th>
                <th>Job Title</th>
                <th>Help Type</th>
                <th>Visit Site</th>
            </tr>
            </thead>

            <tfoot id="filters">
            <tr>
                <th>Name</th>
                <th>Contact</th>
                <th>Industry</th>
                <th>Job Title</th>
                <th>Help Type</th>
                <th>Visit Site</th>
            </tr>
            </tfoot>

            <tbody>
            {% for volunteer in volunteers %}
            <tr>
                <td>
                    <a href="{% url 'view-volunteer' volunteer.pk %}">
                        {{ volunteer.last_name }}, {{ volunteer.first_name }}
                    </a>
                </td>
                <td>
                    {{ volunteer.user.username }}<br>
                    {{ volunteer.phone }}<br>
                    {{ volunteer.address_line1 }}<br>
                    {{ volunteer.address_line2 }}<br>
                    {{ volunteer.city }}, {{ volunteer.state }} {{ volunteer.zipcode }}
                </td>
                <td>
                    {% for occ in volunteer.occupation_set.all %}
                    {{ occ.industry }}<br>
                    {% endfor %}
                </td>
                <td>
                    {% for occ in volunteer.occupation_set.all %}
                    {{ occ.job_title }}<br>
                    {% endfor %}
                </td>
                <td>
                    {% for help_resp in volunteer.helptyperesponse_set.all %}
                    {{ help_resp.help_type.short_name }}
                    {% if help_resp.help_type.has_details %}
                    {{ help_resp.details }}
                    {% endif %}
                    <br>
                    {% endfor %}
                </td>
                <td>
                    {% for site in volunteer.volunteersite_set.all %}
                    {% if site.affirmative %}
                    {{ site.site.name }}
                    {{ site.name }}<br>
                    {% endif %}
                    {% endfor %}
                </td>
                <!--<td>
                    {% for help_resp in volunteer.helptyperesponse_set.all %}
                        {{ help_resp.details }}<br>
                    {% endfor %}
                </td>-->

            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
</div>

{% include "footer.html" %}